---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-159
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/AnandBiradar5657/Argocd-example03.git
  insecure: "false"
  enableLfs: "false"
